Slug enhancements
codelab-app/platform pull request #2184
Opened 2023-01-17 21:18 UTC by mohasarc

## Description

## Video or Image

comming soon...

## Related Issue(s)

Fixes #2142

2023-01-27 10:29 UTC, webberwang requested changes
- [ ] If we enter capital letters, it shouldn't show up in slug
- [ ] The atom shouldn't flash ID or any other data

2023-01-27 10:43 UTC, mohasarc commented
Regarding the capital letters showing up in the slug, that's the default behaviour of the library we're using; however, that wouldn't be registered because names are not allowed to have capital letters.

2023-01-27 18:11 UTC, webberwang requested changes

2023-01-27 18:11 UTC, webberwang commented on libs/frontend/domain/app/src/use-cases/create-app/CreateAppModal.tsx
> +        onChange={(k, v) => {
use `key`, `value` https://wiki.codelab.app/development/fullstack/code-guidelines#avoid-abbreviations

2023-01-27 18:11 UTC, webberwang commented on libs/frontend/domain/app/src/use-cases/update-app/updateAppSchema.ts
> +      type: 'string',
is this required?

2023-01-27 18:11 UTC, webberwang commented on libs/frontend/domain/element/src/use-cases/element/create-element/CreateElementModal.tsx
> +          onChange={(k, v) => {
don't use abbreviations

2023-01-27 18:11 UTC, webberwang commented on libs/frontend/domain/element/src/use-cases/element/create-element/createElementSchema.ts
> +      type: 'string',
not required here

2023-01-27 18:11 UTC, webberwang commented on libs/frontend/domain/element/src/use-cases/element/update-element/UpdateElementForm.tsx
> +            slug: k === 'name' ? slugify(v) : model.slug,
same

2023-01-27 18:11 UTC, webberwang commented on libs/frontend/domain/page/src/use-cases/update-page/UpdatePageModal.tsx
> +            setModel({
this logic has been repeated many times, you can extract to util function

2023-01-28 20:42 UTC, mohasarc commented on libs/frontend/domain/app/src/use-cases/update-app/updateAppSchema.ts
> +      type: 'string',
oh yeah, after the addition of nonEmptyString it deosn't seem to be required anymore.

2023-01-30 15:23 UTC, mohasarc commented on libs/frontend/domain/page/src/use-cases/update-page/UpdatePageModal.tsx
> +            setModel({
I couldn't find a good way to extract this part into a util function, do you have any suggestions?

2023-02-03 03:40 UTC, webberwang requested changes

2023-02-03 03:40 UTC, webberwang commented on libs/frontend/domain/element/src/components/auto-computed-element-name/AutoComputedElementNameField.tsx
> +    useEffect(() => {
couldn't we use a `@computed` method with mobx to derive the name?

2023-02-03 06:37 UTC, mohasarc commented on libs/frontend/domain/element/src/components/auto-computed-element-name/AutoComputedElementNameField.tsx
> +    useEffect(() => {
We're doing so in the mobx store. here, we're only passing the user input to the `computeElementNameService`.

2023-02-03 16:05 UTC, merged