feat: make element/page slugs computed from name in graphql
codelab-app/platform pull request #2264
Opened 2023-02-13 09:40 UTC by mohasarc

## Description

This PR aims at removing slugs creation, update, and storage and make them computed from the name in the backend. Cosequently, the name should be unique and restricted in terms of charachters to have 1 to 1 mapping to the computed slug.

TODO:
- [x] make slugs computed
- [ ] enforce uniqueness on names
- [ ] revise the slugs logic in element to make sure everything is working fine (slugs used to have parent id to make them unique across pages, but names don't)

## Video or Image

Fixes #2246

2023-02-15 11:09 UTC, webberwang commented on libs/frontend/abstract/core/src/domain/app/app.fragment.graphql
> -  slug
needs to be added back?

2023-02-22 16:29 UTC, webberwang requested changes

2023-02-22 16:29 UTC, webberwang commented on libs/backend/graphql/src/resolvers/app/app.resolver.ts
> +export const appSlug = ({ name }: { name: string }) => name.replace(/\s/g, '-')
why don't we use voca here?

2023-02-22 16:29 UTC, webberwang commented on libs/backend/graphql/src/resolvers/element/element.resolver.ts
> +  name.replace(/\s/g, '-')
voca

2023-02-22 16:29 UTC, webberwang commented on libs/backend/graphql/tsconfig.lib.json
> +    "../application/repo-resolvers/resolvers/domain/domain.error.ts",
why is this included?

2023-02-22 16:31 UTC, mohasarc commented on libs/backend/graphql/tsconfig.lib.json
> +    "../application/repo-resolvers/resolvers/domain/domain.error.ts",
this must have happened by mistake, I'll remove it.

2023-02-22 21:01 UTC, merged