fix: remove duplicate form components on export
codelab-app/platform pull request #2556
Opened 2023-04-28 02:57 UTC by amrmuhamedd

## Description
remove duplicate from components on export app

## Video or Image
## Before

https://user-images.githubusercontent.com/47860740/235043638-e4255313-f890-4ff9-a04f-72b495e7f696.mp4

## After

https://user-images.githubusercontent.com/47860740/235043487-cfbd757b-cd0e-4cb8-af7d-ef9172bab04e.mp4

## Related Issue(s)

- #2504 

Fixes

-  #2504

2023-04-28 04:04 UTC, webberwang requested changes
![page_repo_ts_—_platform](https://user-images.githubusercontent.com/26264925/235051468-fa72b9ad-be76-4042-b3bc-dede414e52d5.jpg)

Solution should filter at the source instead

2023-04-30 08:35 UTC, webberwang requested changes

2023-04-30 08:35 UTC, webberwang commented on libs/backend/abstract/core/src/app.interface.ts
> +export interface IExportComponents {
should put in components file

2023-04-30 08:35 UTC, webberwang commented on libs/backend/application/user/src/use-case/export-user-data.ts
> +    components: components,
unnecessary object notation

2023-04-30 08:35 UTC, webberwang commented on libs/backend/domain/app/src/repository/app.repo.ts
> +    await storeRepository.add([component.store]).catch((err) => null)
no need to catch here, since we're not doing anything with the catch

2023-04-30 08:35 UTC, webberwang commented on libs/backend/domain/app/src/repository/app.repo.ts
> +  const pages = await pageRepository.find({ app: { id: app.id } })
Try to move this to ComponentRepository.find(), and pass in component where to this function

2023-04-30 08:35 UTC, webberwang commented on libs/backend/application/user/src/use-case/import-user-data.ts
> +  await importApps(apps, components, owner)
components belong to a user, so importing components should go under `importUserData`

2023-04-30 08:35 UTC, webberwang commented on libs/backend/application/app/src/use-case/import-apps.ts
> +    const importedApp = await createApp(app, components, owner)
component is scoped under user

2023-04-30 08:35 UTC, webberwang commented on libs/backend/application/app/src/use-case/export-components.ts
> +      const { components: Exportedcomponent } = await getComponents(app)
this function should call componentRepository like `export-app`

2023-04-30 08:39 UTC, amrmuhamedd commented on libs/backend/domain/app/src/repository/app.repo.ts
> +    await storeRepository.add([component.store]).catch((err) => null)
if no catch and user have a app it return error validation constrain I add catch to continue and update the app if exist

2023-05-01 06:35 UTC, merged