2831 define app pages order when displayed list of pages
codelab-app/platform pull request #2858
Opened 2023-07-28 05:55 UTC by CreativeDev0809

## Description

Fixed the sort pages of apps with this order: _app, normal pages, 404, 500

## Video or Image

## Related Issue(s)

Fixes #

2023-07-28 07:40 UTC, webberwang requested changes

2023-07-28 07:40 UTC, webberwang commented on libs/frontend/domain/app/src/store/app.service.ts
> +      if (a.name === '_app') {
we should use enum here

2023-07-28 07:40 UTC, webberwang commented on libs/frontend/domain/page/src/use-cases/get-pages/PageList.tsx
> +  console.log(app.pages)
remove the log

2023-07-30 09:38 UTC, webberwang requested changes

2023-07-30 09:38 UTC, webberwang commented on libs/frontend/domain/app/src/store/app.service.ts
> +    enum PageType {
the enum already exists in our project, it's inside shared abstract folder I believe

2023-07-31 01:01 UTC, CreativeDev0809 commented on libs/frontend/domain/app/src/store/app.service.ts
> +    enum PageType {
Fixed using compare with page kind(used enum IPageKind in abstract/core). Please check it.

2023-07-31 17:04 UTC, merged