feat: filter out unused metadata for production website
codelab-app/platform pull request #2889
Opened 2023-08-09 13:36 UTC by nettohadi

## Description

Currently, production websites fetch extensive details about the app/page, including metadata like interfaces, fields, atoms, etc., without determining if this data is essential for the page in view. Moreover, it retrieves metadata for all pages, even when we're viewing just one. This leads to two significant performance issues:

- **Increased Page Size**: Even simple pages are bloated with unnecessary data. This is flagged by Next.js, which warns that the large data size exceeds the optimal threshold, potentially degrading performance. 

- **Expensive Loading Into the Store**: Loading all these interfaces is resource-intensive. Lighthouse performance metrics reveal that even a simple page with a single text element suffers due to the time taken to load the interfaces and fields. This consumes 2 seconds of blocking time, negatively impacting the overall user experience.

<img width="800" alt="Screenshot 2023-05-05 at 18 29 50" src="https://user-images.githubusercontent.com/74900868/236515049-4fab005b-686c-4b84-b0de-cc8bb38f9df2.png">

## What's done in this PR

## Related Issue(s)

Fixes [#2597](https://github.com/codelab-app/platform/issues/2597)

2023-08-09 14:12 UTC, nettohadi commented
I am still trying to remove the interfaces. This may take awhile.

2023-08-10 06:51 UTC, webberwang commented
> I am still trying to remove the interfaces. This might take some time.

Yeah sure it is a complex task

2023-08-15 17:00 UTC, webberwang commented on apps/websites/middleware.ts
> +  const hostname = req.headers.get('host')?.replace(/https?:\/\//g, '')
could convert to new URL and get the hostname

2023-08-15 17:06 UTC, webberwang commented on libs/frontend/abstract/core/src/domain/atom/atom.fragment.graphql
> +fragment AtomLite on Atom {
I used `Preview` for some other queries, but I think both Preview and Lite could be more descriptive. The vocab should relate to where it is used. The ProductionPage naming is much better

2023-08-15 17:07 UTC, webberwang commented on libs/frontend/abstract/core/src/domain/element/element.fragment.graphql
> +fragment ElementLite on Element {
Same here

2023-08-15 17:09 UTC, webberwang commented on libs/frontend/domain/atom/src/store/atom.model.ts
> +    api: typeRef<IInterfaceType>(api?.id ?? ''),
typeRef to an empty string doesn't really make sense (even though it solves the lint)

2023-08-15 17:09 UTC, webberwang commented on libs/frontend/domain/store/src/store/models/store.model.ts
> +    api: typeRef(api?.id ?? '') as Ref<IInterfaceType>,
same

2023-08-16 00:33 UTC, nettohadi commented on apps/websites/middleware.ts
> +  const hostname = req.headers.get('host')?.replace(/https?:\/\//g, '')
Hmm, I've realized that I don't need to use `replace(/https?:\/\//g, '')` because it's already stripped of `http://`.

2023-08-16 00:41 UTC, nettohadi commented on libs/frontend/abstract/core/src/domain/atom/atom.fragment.graphql
> +fragment AtomLite on Atom {
Which name makes more sense: `AtomWithoutInterfaces` or `AtomProduction`?

2023-08-16 00:42 UTC, nettohadi commented on libs/frontend/domain/atom/src/store/atom.model.ts
> +    api: typeRef<IInterfaceType>(api?.id ?? ''),
Will fix this.

2023-08-16 02:23 UTC, nettohadi commented on libs/frontend/domain/atom/src/store/atom.model.ts
> +    api: typeRef<IInterfaceType>(api?.id ?? ''),
Fixed [here](https://github.com/codelab-app/platform/pull/2889/commits/60f1dec84339dad763dafce6efe0de40ec5a3891).I ended up modifying many more files to handle the possibility of an undefined `api`.

2023-08-16 02:37 UTC, nettohadi commented on libs/frontend/domain/atom/src/store/atom.model.ts
> +    api: typeRef<IInterfaceType>(api?.id ?? ''),
Looks like we still have errors. I am fixing them now.

2023-08-16 02:52 UTC, nettohadi commented on libs/frontend/domain/atom/src/store/atom.model.ts
> +    api: typeRef<IInterfaceType>(api?.id ?? ''),
Never mind. it was a false alarm.

2023-08-16 03:46 UTC, nettohadi commented on libs/frontend/domain/store/src/store/models/store.model.ts
> +    api: typeRef(api?.id ?? '') as Ref<IInterfaceType>,
Fixed [here](https://github.com/codelab-app/platform/pull/2889/commits/69d471146ed7b1f708004400b1089cded4803625).

2023-08-17 02:13 UTC, nettohadi commented
@webberwang - As discussed earlier, we'll ensure that empty element props are always assigned their default values. This eliminates the need to fetch the default values from interfaces in production. In essence, we'll synchronize the props with their respective default values during build time. Here is the [commit](https://github.com/codelab-app/platform/pull/2889/commits/96b15e08ace4c0966f76b497f61830fddf423134).

2023-08-17 06:21 UTC, webberwang requested changes

2023-08-17 06:21 UTC, webberwang commented on libs/backend/domain/atom/src/repository/atom.repo.ts
> -            api: connectNodeId(api.id),
connectNodeId can take undefined as arg

2023-08-17 06:21 UTC, webberwang commented on libs/frontend/domain/element/src/use-cases/element/update-element-props/UpdateElementPropsForm.tsx
>      const onSubmit = (data: IPropData) => {
should move this inside the propService.update, or create a new propService.updateWithDefaultValuesApplied or something if the update function needs the original function elsewhere

2023-08-17 12:18 UTC, nettohadi commented on libs/frontend/domain/element/src/use-cases/element/update-element-props/UpdateElementPropsForm.tsx
>      const onSubmit = (data: IPropData) => {
Updated [here](https://github.com/codelab-app/platform/pull/2889/commits/169147986a95234669f297dec6b1491a30df1a87).

2023-08-17 12:25 UTC, nettohadi commented on libs/backend/domain/atom/src/repository/atom.repo.ts
> -            api: connectNodeId(api.id),
Updated [here](https://github.com/codelab-app/platform/pull/2889/commits/8c40acedee78b81bca7639e61311826459e76dad).

2023-08-17 12:38 UTC, nettohadi commented on libs/frontend/abstract/core/src/domain/atom/atom.fragment.graphql
> +fragment AtomLite on Atom {
Updated [here](https://github.com/codelab-app/platform/pull/2889/commits/be75d3e9d04ec99d7b0084c36f5be40cc09b5ece).

2023-08-17 12:55 UTC, nettohadi commented on libs/frontend/abstract/core/src/domain/element/element.fragment.graphql
> +fragment ElementLite on Element {
Updated [here](https://github.com/codelab-app/platform/pull/2889/commits/be75d3e9d04ec99d7b0084c36f5be40cc09b5ece).

2023-08-18 05:42 UTC, webberwang requested changes

2023-08-18 05:42 UTC, webberwang commented on libs/backend/domain/store/src/model/store.model.ts
> +    this.api = api ?? { id: '' }
makes more sense to have `api | undefined` or `api | null`

2023-08-18 05:42 UTC, webberwang commented on libs/frontend/domain/atom/src/use-cases/get-atoms/AtomsTreeItem.tsx
> +      ? (typeRef(interfaceId) as Ref<IInterfaceType>)
I believe typeRef is generic and requires no casting

2023-08-18 05:42 UTC, webberwang commented on libs/shared/data/test/src/atoms.data.ts
> +    id: atom.api?.id ?? '',
since is required here, we should throw an error in the map callback if the id doesn't exist

2023-08-18 13:48 UTC, nettohadi commented on libs/frontend/domain/atom/src/use-cases/get-atoms/AtomsTreeItem.tsx
> +      ? (typeRef(interfaceId) as Ref<IInterfaceType>)
Fixed [here](https://github.com/codelab-app/platform/pull/2889/commits/6db96dca731f159cfed007b1dd3c845ac99e534e).

2023-08-18 13:49 UTC, nettohadi commented on libs/shared/data/test/src/atoms.data.ts
> +    id: atom.api?.id ?? '',
Updated [here](https://github.com/codelab-app/platform/pull/2889/commits/6922102e6af31c4a2f0c5066c4ebe479ccdc906f).

2023-08-18 13:50 UTC, nettohadi commented on libs/backend/domain/store/src/model/store.model.ts
> +    this.api = api ?? { id: '' }
Updated [here](https://github.com/codelab-app/platform/pull/2889/commits/49743b00eede912d1716486f769fd7edf0b86217).

2023-08-19 18:49 UTC, vladyslav-polishchuk commented on libs/frontend/abstract/core/src/domain/atom/atom.fragment.graphql
> +  owner {
Do you think it is possible to omit `owner` and `tags` for production?

2023-08-21 06:12 UTC, nettohadi commented on libs/frontend/abstract/core/src/domain/atom/atom.fragment.graphql
> +  owner {
Looking into this.

2023-08-21 06:31 UTC, nettohadi commented on libs/frontend/abstract/core/src/domain/atom/atom.fragment.graphql
> +  owner {
I've tested this, and everything appears to work fine in production website without the `owner` and `tags`. Any concern if we remove them, @webberwang?

2023-08-21 09:00 UTC, webberwang commented on libs/frontend/abstract/core/src/domain/atom/atom.fragment.graphql
> +  owner {
seems okay without it

2023-08-21 09:01 UTC, webberwang requested changes
some merge conflicts after master was updated thanks

2023-08-21 12:36 UTC, nettohadi commented
> some merge conflicts after master was updated thanks

Will resolve the conflicts.

2023-08-23 04:04 UTC, merged