fix: lint and integration job on ci
codelab-app/platform pull request #3082
Opened 2023-10-14 07:51 UTC by vladyslav-polishchuk

## Description

## Video or Image

## Related Issue(s)

Fixes #

2023-10-14 07:52 UTC, vladyslav-polishchuk commented on libs/frontend/application/app/src/use-cases/app-development/app-development.endpoints.graphql
The `primitiveTypes`, `reactNodeTypes` and `renderPropTypes` already included in the query several lines above (before `resources`)

2023-10-14 07:52 UTC, vladyslav-polishchuk commented on libs/frontend/application/app/src/use-cases/app-development/app-development.endpoints.graphql
> -  # Load system types
The primitiveTypes, reactNodeTypes and renderPropTypes already included in the query several lines above (before resources)

2023-10-16 09:05 UTC, webberwang requested changes

2023-10-16 09:05 UTC, webberwang commented on libs/backend/application/admin/src/use-case/seed-framework/import-export.i.spec.ts
> -jest.setTimeout(240000)
Instead of increasing timeout, we can seed maybe 20 random atoms each time. This means we don't have to seed so much data, and the randomness will likely encompass all atoms over the course of multiple ci runs

2023-10-17 12:16 UTC, webberwang requested changes
I'm thinking another approach
![import-admin-data_command_service_ts_—_codelab__Workspace_](https://github.com/codelab-app/platform/assets/26264925/ba71c381-19aa-4757-809d-4a8ddc24249d)

We can use an existing Stage enum, pick test & dev since those are the 2 different scenarios

then similar to `if(baseDataPaths)`, we can set a boolean property on ReadAdminDataService

we then shuffle and limit say some arbitrary hard coded value

2023-10-17 16:23 UTC, vladyslav-polishchuk commented
> I'm thinking another approach ![import-admin-data_command_service_ts_—codelab__Workspace](https://user-images.githubusercontent.com/26264925/275828299-ba71c381-19aa-4757-809d-4a8ddc24249d.jpg)
> 
> We can use an existing Stage enum, pick test & dev since those are the 2 different scenarios
> 
> then similar to `if(baseDataPaths)`, we can set a boolean property on ReadAdminDataService
> 
> we then shuffle and limit say some arbitrary hard coded value

A couple of questions about this approach:

1. There are 4 stages exist: `dev`, `prod`, `test` and `ci`. This logic should be implemented for `ci` only, right? `prod` looks like is used only with terraform commands, `test` is used in commit hooks (probably need to run integration test with all atoms in this case), `dev` is the same, probably better run on all atoms, and the `ci` is the only case we want?

2. Currently the best way to understand the `stage` is CI is 
```
this.readAdminDataService.partiallySeed =
      process.env['NX_TASK_TARGET_CONFIGURATION'] === Stage.CI
```
but this seems a bit odd. Maybe you know better approach?

2023-10-17 17:06 UTC, webberwang commented
> > I'm thinking another approach ![import-admin-data_command_service_ts_—codelab__Workspace](https://user-images.githubusercontent.com/26264925/275828299-ba71c381-19aa-4757-809d-4a8ddc24249d.jpg)
> > We can use an existing Stage enum, pick test & dev since those are the 2 different scenarios
> > then similar to `if(baseDataPaths)`, we can set a boolean property on ReadAdminDataService
> > we then shuffle and limit say some arbitrary hard coded value
> 
> A couple of questions about this approach:
> 
> 1. There are 4 stages exist: `dev`, `prod`, `test` and `ci`. This logic should be implemented for `ci` only, right? `prod` looks like is used only with terraform commands, `test` is used in commit hooks (probably need to run integration test with all atoms in this case), `dev` is the same, probably better run on all atoms, and the `ci` is the only case we want?
> 2. Currently the best way to understand the `stage` is CI is
> 
> ```
> this.readAdminDataService.partiallySeed =
>       process.env['NX_TASK_TARGET_CONFIGURATION'] === Stage.CI
> ```
> 
> but this seems a bit odd. Maybe you know better approach?

Nevermind seems a boolean value of `partialSeed: boolean` or something could work

2023-10-20 14:08 UTC, webberwang requested changes

2023-10-20 14:08 UTC, webberwang commented on libs/backend/application/admin/src/use-case/seed-framework/import-export.i.spec.ts
> +    const pathsToCompare = [
I think it's more clear if we construct a `Record<ExportFilePath, ImportFilePath>`

Then we transform into `Record<ExportFileContent, ImportFileContent>` to compare them

2023-10-20 14:10 UTC, merged