fix: login into production
codelab-app/platform pull request #3119
Opened 2023-11-04 09:04 UTC by vladyslav-polishchuk

## Description

## Video or Image

## Related Issue(s)

Fixes #

2023-11-05 00:33 UTC, webberwang requested changes

2023-11-05 00:33 UTC, webberwang commented on scripts/vercel/platform-api/install.sh
> +cp -r data ./apps/platform-api
no need to copy right? if we are only running migration locally

2023-11-05 09:33 UTC, vladyslav-polishchuk commented on scripts/vercel/platform-api/install.sh
> +cp -r data ./apps/platform-api
Currently, `setup-dev` is called after login to populate system data and it fails without `data/export-v3/system/types/system-types.json`. So if we do not need to run migration directly from production UI - we may still need at least this file to be copied so that login command successes.

Or alternatively, we can call `setup-dev` only from local environment, so it is not getting called in production each time any user logs in. What do you think?

2023-11-05 09:34 UTC, vladyslav-polishchuk commented on scripts/vercel/platform-api/install.sh
> +cp -r data ./apps/platform-api
Also, If we plan to run seed for production from local environment, do I need to continue work with bull queues? Since from local machine there is no timeout of how long the seed request may be running

2023-11-05 16:10 UTC, webberwang commented on scripts/vercel/platform-api/install.sh
> +cp -r data ./apps/platform-api
Sure if we don't need `setup-dev` on production we can call locally only, so we can remove that part.

I hadn't thought of that, seems like we don't need queue for this instance. We can keep whatever code we have and pause on this.

The queue might come in useful in the future though

2023-11-05 17:29 UTC, vladyslav-polishchuk commented on scripts/vercel/platform-api/install.sh
> +cp -r data ./apps/platform-api
I will create and cancel the PR with the queue, so that it can be looked up easily through GitHub UI if we decide to continue work on it at some point in the future

2023-11-08 08:02 UTC, vladyslav-polishchuk commented
Will retarget to `dev` branch, since there are already fixed ts build errors

2023-11-08 08:02 UTC, closed without merging