fix: error during export
codelab-app/platform pull request #3132
Opened 2023-11-11 08:51 UTC by vladyslav-polishchuk

## Description

- an error was thrown during atoms export (too many opened DB connections) because all atoms were imported in parallel. Instead import 10 at a time
- allow to specify `selectionSet` in backend repo classes for more effective queries. In future can benefit from this also by updating `exists` method on all repos to fetch only record `id` instead of getting entire record with all relationships

## Video or Image

## Related Issue(s)

Fixes #

2023-11-11 19:37 UTC, webberwang requested changes

2023-11-11 19:37 UTC, webberwang commented on libs/backend/application/atom/src/services/atom.application.service.ts
> +    for (const atomsChunk of atomChunks) {
instead of chunking would it work if we used `for of` instead of `promise.all`?

2023-11-11 20:21 UTC, vladyslav-polishchuk commented on libs/backend/application/atom/src/services/atom.application.service.ts
> +    for (const atomsChunk of atomChunks) {
And use `await` inside, meaning import just one after another? Yes, this also works

2023-11-12 09:40 UTC, webberwang commented on libs/backend/application/atom/src/services/atom.application.service.ts
> +    for (const atomsChunk of atomChunks) {
yeah let's just do that without chunk, seems simpler

2023-11-12 09:41 UTC, merged